"""rozstawienie

Revision ID: 2bc0278e2b3a
Revises: 
Create Date: 2021-01-08 03:18:21.640370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2bc0278e2b3a"
down_revision = None
branch_labels = ("default",)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nazwa", sa.String(length=120), nullable=False),
        sa.Column("pierwszy_param", sa.String(length=120), nullable=False),
        sa.Column("drugi_param", sa.String(length=120), nullable=False),
        sa.Column("trzeci_param", sa.String(length=120), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "produkty",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nazwa", sa.String(length=120), nullable=False),
        sa.Column("stan_mag", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "saldo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wartosc_salda", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("saldo")
    op.drop_table("produkty")
    op.drop_table("history")
    # ### end Alembic commands ###
